Remove genomelake
kipoi/kipoi pull request #596
Opened 2021-07-02 12:07 UTC by haimasree

genomelake removed as discussed. I have used your one_hot_encode_sequence and the extractors from genomelake and put them in a separate file for future reference. I changed test_github_permalink to include a model which does not have genomelake as dependency. I would get the following error otherwise - 
```
module genomelake not found
```
Is that okay? 

I am keeping this pr open - we can discuss on monday.

2021-07-13 17:31 UTC, Avsecz requested changes

2021-07-13 17:31 UTC, Avsecz commented on docs/templates/contributing/04_Writing_dataloader.py.md
>  class SeqDataset(Dataset):
Could be replaced by kipoiseq.FastaStringExtractor followed by kipoiseq.transforms.one_hot_dna

2021-07-13 17:31 UTC, Avsecz commented on example/models/extended_coda/dataloader.py
> +from kipoi.helper import ArrayExtractor
This test could be removed

2021-07-13 17:31 UTC, Avsecz commented on example/models/non_bedinput_model/dataloader.py
> +from kipoi.helper import BaseExtractor, FastaExtractor, NUM_SEQ_CHARS, one_hot_encode_sequence
Could copy in BaseExtractor from genomelake here and use FastaStringExtractor from kipoiseq

2021-07-13 17:31 UTC, Avsecz commented on example/models/pyt/dataloader.py
> +from kipoi.helper import FastaExtractor
Use FastaStringExtractor from kipoiseq

2021-07-13 17:31 UTC, Avsecz commented on example/models/rbp/dataloader.py
> +from kipoi.helper import BaseExtractor, FastaExtractor, NUM_SEQ_CHARS, one_hot_encode_sequence
See above

2021-07-13 17:31 UTC, Avsecz commented on kipoi/helper.py
> +import six
Please remove this

2021-07-20 16:47 UTC, haimasree commented
I have addressed all the review and have moved one_hot_dna to https://github.com/kipoi/kipoiseq/tree/add-one-hot-encode. kipoiseq branch needs to be updated after one_hot_dna is added to kipoiseq's master branch

2021-07-20 16:47 UTC, merged